### ISSUE TITLE
function capacity 4096 has been exceeded for this scope when importing Microsoft.Graph to AA in 5.1 runtime

### ISSUE THREAD

**Issue by silentmark** [microsoftgraph/msgraph-sdk-powershell#1449]
Hi, 

i couldn't find anywhere similar issue. I cannot import Microsoft.Graph module into Azure Automation account using runtime 5.1, when importing with preview 7.1 runtime, the import is successful (as there is no variable limit), however there is no version information for this module, instead there is only: "WARNING: Selecte" written . The full error message is listed below.

Not sure if there is anything that can be done on msgraph-sdk-powershell side. 

```Error importing the module Microsoft.Graph. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: While importing the module, an error occurred while processing the module content. Internal error message: Function Update-MgShareListContentTypeColumnLink cannot be created because function capacity 4096 has been exceeded for this scope.. at Orchestrator.Activities.SetModuleVersion.ExecuteInternal(CodeActivityContext context, String moduleName, ModuleLanguage moduleLanguage, String pythonModuleVersion, String modulePath, Guid accountId, Guid moduleVersionId, Int64 moduleContentByteSize, String storageUri, Int32 moduleVersion) at Orchestrator.Activities.SetModuleVersion.Execute(CodeActivityContext context) at System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager) at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)```

**Comment by peombwa** [comment]
@silentmark, this is a known [Windows PowerShell 5.1 limitation](https://github.com/PowerShell/PowerShell/issues/2221) that was resolved in PowerShell core.

Your options are:
- Use the latest version of PowerShell 7+ (highly recommended).
- Only load the Microsoft.Graph modules you need. You find the complete reference of all modules at https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.applications/?view=graph-powershell-1.0.
- Set [$maximumfunctioncount](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md#maximumfunctioncount) variable to its max value, 32768.

**Comment by peombwa** [comment]
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1186.

**Comment by RyanHill-MSFT** [comment]
@peombwa just an FYI that this is still an issue for some folks. Please see https://docs.microsoft.com/en-us/answers/questions/964238/index.html.
