### ISSUE TITLE
Microsoft.Graph 2.27.0 New-MgUser fails when called after Get-MgSubscribedSku

### ISSUE THREAD

**Issue by jaspain** [microsoftgraph/msgraph-sdk-powershell#3315]
### Describe the bug

With Microsoft.Graph 2.27.0, I see the following error on calling `New-MgUser`: "New-MgUser_Create: A value is required for property 'displayName' of resource 'User'." Without the preceding call to `Get-MgSubscribedSku`, the error does not occur.

With Microsoft.Graph 2.26.1, the error is different: "New-MgUser_Create: Cannot convert the literal '987654' to the expected type 'Edm.String'." (see below).

With Microsoft.Graph 2.25.0, the error does not occur (see further below). Thank you.

**Microsoft.Graph 2.27.0:**
```
PowerShell 7.5.1
The host is domain joined. Hybrid users can be managed.
PowerShell Core 7.5.1 modules required for M365Management.psm1:
ExchangeOnlineManagement v3.7.2 available (requires >= 3.7.2)
Microsoft.Graph v2.27.0 available (requires >= 2.20.0)
MicrosoftTeams v7.0.0 available (requires >= 6.9.0)
Connecting to Microsoft Exchange Online...
Connected to Exchange Online organization Cincinnati Country Day School
Connecting to Microsoft Graph...
Connected to Microsoft Graph as PowerShell System Administration
Connecting to Microsoft Teams...
Loaded Module 'Microsoft.Teams.ConfigAPI.Cmdlets'
Connected to Microsoft Teams tenant ID 3d7f44db-e0c8-4f1d-a957-27d70737ddb4
[M365PS] C:\Users\simonn\Downloads> Get-MgSubscribedSku -All

Id                                                                        AccountId                            AccountN
                                                                                                               ame
--                                                                        ---------                            --------
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_1f2f344a-700d-42c9-9427-5cea1d5d7ba6 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_87bbbc60-4754-4998-8c88-227dca264858 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_78e66a63-337a-4a9a-8959-41c6654dfb56 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_6470687e-a428-4b7a-bef2-8a291ad947c9 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_e97c048c-37a4-45fb-ab50-922fbf07a370 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_e82ae690-a2d5-4d76-8d30-7c6e01e6022e 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_f30db892-07e9-47e9-837c-80727f46fd3d 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_ad9c22b3-52d7-4e7e-973c-88121ea96436 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_a4e376bd-c61e-4618-9901-3fc0cb1b88bb 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_31d57bc7-3a05-4867-ab53-97a17835a411 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_a403ebcc-fae0-4ca2-8c8c-7a907fd6c235 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_c7e9d9e6-1981-4bf3-bb50-a5bdfaa06fb2 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_420c7602-7f70-4895-9394-d3d679ea36fb 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_4b590615-0888-425a-a965-b3bf7789848d 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_52ea0e27-ae73-4983-a08f-13561ebdb823 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_0e142028-345e-45da-8d92-8bfd4093bbb9 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_143f2028-783c-4ac8-b384-19562dfcd8d0 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_bf95fd32-576a-4742-8d7a-6dc4940b9532 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_c25e2b36-e161-4946-bef2-69239729f690 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_5b631642-bd26-49fe-bd20-1daaa972ef80 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…

[M365PS] C:\Users\simonn\Downloads> $pp = @{ Password = 'Hnni63ff'; ForceChangePasswordNextSignIn = $False }
[M365PS] C:\Users\simonn\Downloads> $bp = @{
>>     UserPrincipalName   = 'tchtest07@countryday.net'
>>     EmployeeID          = '987654'
>>     PasswordPolicies    = 'DisablePasswordExpiration'
>>     UsageLocation       = 'US'
>>     JobTitle            = 'Faculty Test, Technology'
>>     Surname             = 'Teacher07'
>>     Department          = 'TestUser'
>>     MailNickname        = 'tchtest07'
>>     PasswordProfile     = $pp
>>     AccountEnabled      = $True
>>     GivenName           = 'Test'
>>     DisplayName         = 'Teacher07, Test'
>> }
[M365PS] C:\Users\simonn\Downloads> New-MgUser -BodyParameter $bp -ErrorAction Stop
New-MgUser_Create: A value is required for property 'displayName' of resource 'User'.

Status: 400 (BadRequest)
ErrorCode: Request_BadRequest
Date: 2025-05-09T15:19:48

Headers:
Cache-Control                 : no-cache
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : eea789df-d463-4d59-83aa-6643be396367
client-request-id             : 47112bad-2b22-4125-b36c-aa541edc85fd
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"North Central US","Slice":"E","Ring":"4","ScaleUnit":"004","RoleInstance":"CH01EPF00003EC6"}}
x-ms-resource-unit            : 1
Date                          : Fri, 09 May 2025 15:19:47 GMT


  Recommendation: See service error codes: https://learn.microsoft.com/graph/errors

```

**Microsoft.Graph 2.26.1:**
```
PowerShell 7.5.1
The host is domain joined. Hybrid users can be managed.
PowerShell Core 7.5.1 modules required for M365Management.psm1:
ExchangeOnlineManagement v3.7.2 available (requires >= 3.7.2)
Microsoft.Graph v2.26.1 available (requires >= 2.26.1)
MicrosoftTeams v7.0.0 available (requires >= 6.9.0)
Connecting to Microsoft Exchange Online...
Connected to Exchange Online organization Cincinnati Country Day School
Connecting to Microsoft Graph...
Connected to Microsoft Graph as PowerShell System Administration
Connecting to Microsoft Teams...
Loaded Module 'Microsoft.Teams.ConfigAPI.Cmdlets'
Connected to Microsoft Teams tenant ID 3d7f44db-e0c8-4f1d-a957-27d70737ddb4
[M365PS] C:\Users\simonn\Downloads> Get-MgSubscribedSku -All

Id                                                                        AccountId                            AccountN
                                                                                                               ame
--                                                                        ---------                            --------
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_1f2f344a-700d-42c9-9427-5cea1d5d7ba6 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_87bbbc60-4754-4998-8c88-227dca264858 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_78e66a63-337a-4a9a-8959-41c6654dfb56 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_6470687e-a428-4b7a-bef2-8a291ad947c9 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_e97c048c-37a4-45fb-ab50-922fbf07a370 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_e82ae690-a2d5-4d76-8d30-7c6e01e6022e 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_f30db892-07e9-47e9-837c-80727f46fd3d 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_ad9c22b3-52d7-4e7e-973c-88121ea96436 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_a4e376bd-c61e-4618-9901-3fc0cb1b88bb 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_31d57bc7-3a05-4867-ab53-97a17835a411 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_a403ebcc-fae0-4ca2-8c8c-7a907fd6c235 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_c7e9d9e6-1981-4bf3-bb50-a5bdfaa06fb2 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_420c7602-7f70-4895-9394-d3d679ea36fb 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_4b590615-0888-425a-a965-b3bf7789848d 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_52ea0e27-ae73-4983-a08f-13561ebdb823 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_0e142028-345e-45da-8d92-8bfd4093bbb9 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_143f2028-783c-4ac8-b384-19562dfcd8d0 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_bf95fd32-576a-4742-8d7a-6dc4940b9532 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_c25e2b36-e161-4946-bef2-69239729f690 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_5b631642-bd26-49fe-bd20-1daaa972ef80 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…

[M365PS] C:\Users\simonn\Downloads> $pp = @{ Password = 'Hnni63ff'; ForceChangePasswordNextSignIn = $False }
[M365PS] C:\Users\simonn\Downloads> $bp = @{
>>     UserPrincipalName   = 'tchtest07@countryday.net'
>>     EmployeeID          = '987654'
>>     PasswordPolicies    = 'DisablePasswordExpiration'
>>     UsageLocation       = 'US'
>>     JobTitle            = 'Faculty Test, Technology'
>>     Surname             = 'Teacher07'
>>     Department          = 'TestUser'
>>     MailNickname        = 'tchtest07'
>>     PasswordProfile     = $pp
>>     AccountEnabled      = $True
>>     GivenName           = 'Test'
>>     DisplayName         = 'Teacher07, Test'
>> }
[M365PS] C:\Users\simonn\Downloads> New-MgUser -BodyParameter $bp -ErrorAction Stop
New-MgUser_Create: Cannot convert the literal '987654' to the expected type 'Edm.String'.

Status: 400 (BadRequest)
ErrorCode: Request_BadRequest
Date: 2025-05-09T14:59:51

Headers:
Cache-Control                 : no-cache
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 2e608444-e62c-4999-8f70-ec16e4c62e5b
client-request-id             : a4da9637-fd09-48ee-90e3-36ddc7aca496
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"East US 2","Slice":"E","Ring":"5","ScaleUnit":"005","RoleInstance":"BN2PEPF000079A6"}}
x-ms-resource-unit            : 1
Date                          : Fri, 09 May 2025 14:59:50 GMT


  Recommendation: See service error codes: https://learn.microsoft.com/graph/errors
```

**Microsoft.Graph 2.25.0**
```
PowerShell 7.5.1
The host is domain joined. Hybrid users can be managed.
PowerShell Core 7.5.1 modules required for M365Management.psm1:
ExchangeOnlineManagement v3.7.2 available (requires >= 3.7.2)
Microsoft.Graph v2.25.0 available (requires >= 2.20.0)
MicrosoftTeams v7.0.0 available (requires >= 6.9.0)
Connecting to Microsoft Exchange Online...
Connected to Exchange Online organization Cincinnati Country Day School
Connecting to Microsoft Graph...
Connected to Microsoft Graph as PowerShell System Administration
Connecting to Microsoft Teams...
Loaded Module 'Microsoft.Teams.ConfigAPI.Cmdlets'
Connected to Microsoft Teams tenant ID 3d7f44db-e0c8-4f1d-a957-27d70737ddb4
[M365PS] C:\Users\simonn\Downloads> Get-MgSubscribedSku -All

Id                                                                        AccountId                            AccountN
                                                                                                               ame
--                                                                        ---------                            --------
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_1f2f344a-700d-42c9-9427-5cea1d5d7ba6 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_87bbbc60-4754-4998-8c88-227dca264858 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_78e66a63-337a-4a9a-8959-41c6654dfb56 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_6470687e-a428-4b7a-bef2-8a291ad947c9 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_e97c048c-37a4-45fb-ab50-922fbf07a370 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_e82ae690-a2d5-4d76-8d30-7c6e01e6022e 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_f30db892-07e9-47e9-837c-80727f46fd3d 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_ad9c22b3-52d7-4e7e-973c-88121ea96436 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_a4e376bd-c61e-4618-9901-3fc0cb1b88bb 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_31d57bc7-3a05-4867-ab53-97a17835a411 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_a403ebcc-fae0-4ca2-8c8c-7a907fd6c235 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_c7e9d9e6-1981-4bf3-bb50-a5bdfaa06fb2 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_420c7602-7f70-4895-9394-d3d679ea36fb 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_4b590615-0888-425a-a965-b3bf7789848d 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_52ea0e27-ae73-4983-a08f-13561ebdb823 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_0e142028-345e-45da-8d92-8bfd4093bbb9 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_143f2028-783c-4ac8-b384-19562dfcd8d0 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_bf95fd32-576a-4742-8d7a-6dc4940b9532 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_c25e2b36-e161-4946-bef2-69239729f690 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_5b631642-bd26-49fe-bd20-1daaa972ef80 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…

[M365PS] C:\Users\simonn\Downloads> $pp = @{ Password = 'Hnni63ff'; ForceChangePasswordNextSignIn = $False }
[M365PS] C:\Users\simonn\Downloads> $bp = @{
>>     UserPrincipalName   = 'tchtest07@countryday.net'
>>     EmployeeID          = '987654'
>>     PasswordPolicies    = 'DisablePasswordExpiration'
>>     UsageLocation       = 'US'
>>     JobTitle            = 'Faculty Test, Technology'
>>     Surname             = 'Teacher07'
>>     Department          = 'TestUser'
>>     MailNickname        = 'tchtest07'
>>     PasswordProfile     = $pp
>>     AccountEnabled      = $True
>>     GivenName           = 'Test'
>>     DisplayName         = 'Teacher07, Test'
>> }
[M365PS] C:\Users\simonn\Downloads> New-MgUser -BodyParameter $bp -ErrorAction Stop

DisplayName     Id                                   Mail UserPrincipalName
-----------     --                                   ---- -----------------
Teacher07, Test a4c6f5d3-6257-44b8-9ec5-1c70dbd320ca      tchtest07@countryday.net
```

### Expected behavior

The error would not occur in Microsoft.Graph 2.27.0.

### How to reproduce

Steps to reproduce are shown in the above error description.

### SDK Version

2.27.0

### Latest version known to work for scenario above?

2.25.0

### Known Workarounds

Revert to Microsoft.Graph 2.25.0

### Debug output

See attached Graph Error 2.27.0 Debug Log.txt.

### Configuration

Windows 11 24H2 x64 or Windows Server 2025 x64
```
[M365PS] C:\Users\simonn\Downloads> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.5.1
PSEdition                      Core
GitCommitId                    7.5.1
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Other information

[Graph Error 2.27.0 Debug Log.txt](https://github.com/user-attachments/files/20125015/Graph.Error.2.27.0.Debug.Log.txt)

**Comment by jaspain** [comment]
The error no longer occurs in Microsoft.Graph 2.28.0.

```
PowerShell 7.5.1
WARNING: The host is not domain joined. Hybrid users cannot be managed.
Required modules for Initialize-M365Management.ps1 in PowerShell Core 7.5.1
Available ExchangeOnlineManagement, v3.7.2 (3.7.2 minimum required)
Available Microsoft.Graph, v2.28.0 (2.25.0 minimum required)
Available MicrosoftTeams, v7.0.0 (6.9.0 minimum required)
Connecting to Microsoft Exchange Online...
Connected to Exchange Online organization Cincinnati Country Day School
Connecting to Microsoft Graph...
Connected to Microsoft Graph as PowerShell System Administration
Connecting to Microsoft Teams...
Loaded Module 'Microsoft.Teams.ConfigAPI.Cmdlets'
Connected to Microsoft Teams tenant ID 3d7f44db-e0c8-4f1d-a957-27d70737ddb4
[M365PS] C:\Users\AzureAdmin\Downloads> Get-MgSubscribedSku -All

Id                                                                        AccountId                            AccountN
                                                                                                               ame
--                                                                        ---------                            --------
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_1f2f344a-700d-42c9-9427-5cea1d5d7ba6 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_87bbbc60-4754-4998-8c88-227dca264858 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_78e66a63-337a-4a9a-8959-41c6654dfb56 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_6470687e-a428-4b7a-bef2-8a291ad947c9 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_e97c048c-37a4-45fb-ab50-922fbf07a370 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_e82ae690-a2d5-4d76-8d30-7c6e01e6022e 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_f30db892-07e9-47e9-837c-80727f46fd3d 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_ad9c22b3-52d7-4e7e-973c-88121ea96436 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_a4e376bd-c61e-4618-9901-3fc0cb1b88bb 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_31d57bc7-3a05-4867-ab53-97a17835a411 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_a403ebcc-fae0-4ca2-8c8c-7a907fd6c235 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_c7e9d9e6-1981-4bf3-bb50-a5bdfaa06fb2 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_420c7602-7f70-4895-9394-d3d679ea36fb 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_4b590615-0888-425a-a965-b3bf7789848d 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_52ea0e27-ae73-4983-a08f-13561ebdb823 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_0e142028-345e-45da-8d92-8bfd4093bbb9 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_143f2028-783c-4ac8-b384-19562dfcd8d0 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_bf95fd32-576a-4742-8d7a-6dc4940b9532 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_c25e2b36-e161-4946-bef2-69239729f690 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…
3d7f44db-e0c8-4f1d-a957-27d70737ddb4_5b631642-bd26-49fe-bd20-1daaa972ef80 3d7f44db-e0c8-4f1d-a957-27d70737ddb4 country…

[M365PS] C:\Users\AzureAdmin\Downloads> $pp = @{ Password = 'Hnni63ff'; ForceChangePasswordNextSignIn = $False }
[M365PS] C:\Users\AzureAdmin\Downloads> $bp = @{
>>     UserPrincipalName   = 'tchtest07@countryday.net'
>>     EmployeeID          = '987654'
>>     PasswordPolicies    = 'DisablePasswordExpiration'
>>     UsageLocation       = 'US'
>>     JobTitle            = 'Faculty Test, Technology'
>>     Surname             = 'Teacher07'
>>     Department          = 'TestUser'
>>     MailNickname        = 'tchtest07'
>>     PasswordProfile     = $pp
>>     AccountEnabled      = $True
>>     GivenName           = 'Test'
>>     DisplayName         = 'Teacher07, Test'
>> }
[M365PS] C:\Users\AzureAdmin\Downloads>
[M365PS] C:\Users\AzureAdmin\Downloads> New-MgUser -BodyParameter $bp -ErrorAction Stop

DisplayName     Id                                   Mail UserPrincipalName
-----------     --                                   ---- -----------------
Teacher07, Test 28c9b3a1-ee08-4e48-a74d-4b352ffe8b1b      tchtest07@countryday.net
```

**Comment by timayabi2020** [comment]
Closing this issue as it has been resolved in the latest SDK 2.28.0

**Comment by gazbea** [comment]
This still does not work. Having the same issue on the latest SDK
