### ISSUE TITLE
Get-MgTeamChannelMember for private channel failed (Failed to execute GetThreadRosterAsync)

### ISSUE THREAD

**Issue by jolscr** [microsoftgraph/msgraph-sdk-powershell#3321]
### Describe the bug

Hi,

Since the **evening of May 10th**, the cmdlets below have been throwing errors when **targeting private channels** with cmdlet "**Get-MgTeamChannelMember**", while they still work as expected with standard channels.
The issue appears with Microsoft Graph PowerShell SDK version 2.27.0 and also persists in the latest version 2.28.0.

It seems to be a permissions-related issue, but the necessary Microsoft Graph permissions are already granted I think.

![Image](https://github.com/user-attachments/assets/f225aa0a-4f6e-4bf4-86fd-0e974eaedbbe)

![Image](https://github.com/user-attachments/assets/81f9f7c3-31a3-43ef-a06f-c9014e39e538)

### Expected behavior

Cmdlets should work for both standard and private channels as long as the required Microsoft Graph permissions are granted, regardless of the SDK version (2.27.0 or 2.28.0).

### How to reproduce

```powershell
Connect-MgGraph -ClientId $clientId -TenantId $tenantId -CertificateThumbprint $certificateThumbprint -ErrorAction:Stop

Get-MgTeamChannelMember -TeamId $TID -ChannelId $CID
``` 

### SDK Version

2.28.0

### Debug output

<details><summary>Click to expand log</summary>
```

```powershell
PS C:\Users\ABC> Get-MgTeamChannelMember -TeamId $TID-ChannelId $CID

Get-MgTeamChannelMember_List: Failed to execute GetThreadRosterAsync.

Status: 403 (Forbidden)
ErrorCode: Forbidden
Date: 2025-05-13T08:13:16

Headers:
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 03da123d-d94d-4a34-b384-2639450f2a8f
client-request-id             : 9d398a3b-f61d-4cb1-acc6-75d57d3b5b54
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Switzerland North","Slice":"E","Ring":"3","ScaleUnit":"000","RoleInstance":"ZR1PEPF0000225F"}}
Date                          : Tue, 13 May 2025 08:13:15 GMT
``` 

```
</details>


### Configuration

Name                           Value
----                           -----
PSVersion                      7.4.7
PSEdition                      Core
GitCommitId                    7.4.7
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### Other information

_No response_

**Comment by jolscr** [comment]
Anyone have same issue with SDK 2.28.0 when requesting channel membership ?
`Get-MgTeamChannelMember -TeamId $TID -ChannelId $CID`

same issue here https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/3296

**Comment by jolscr** [comment]
same issue here https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/3296

**Comment by jolscr** [comment]
Issue persist with sdk 2.29.0 ! Is there anybody here ? 2 month waiting for a fix...
Get-MgTeamChannelMember call https://graph.microsoft.com/v1.0/teams/teamsid/channels/chanelid/allMembers
but it works if we invoke the uri with **members** and not **allMembers**

**Comment by zhead13** [comment]
Same issue..same error on Standard Channels let alone Private Channels

**Comment by DylanHover3** [comment]
Would like to see a resolution for this issue.

**Comment by jolscr** [comment]
Same with Graph SDK 2.31.0
Nobody uses this in the whole world? Strange...

**Comment by Tiffoox** [comment]
Same issue. Can you resolve this ?

**Comment by MIchaelMainer** [comment]
Service API owner needs to investigate whether the AllMembers URL is valid and/or working as expected.

**Comment by gavinbarron** [comment]
It appears as though we have two issues:
- The Service issue on [`GET /teams/{team-id}/channels/{channel-id}/allMembers`](https://learn.microsoft.com/en-us/graph/api/channel-list-allmembers?view=graph-rest-1.0&tabs=http)
- We don't generate a cmdlet that wraps the [`GET /teams/{team-id}/channels/{channel-id}/members`](https://learn.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&tabs=http) request

```PowerShell
 gavinbarron  Find-MgGraphCommand -Uri ".*/members$" -Method GET

   APIVersion: v1.0

Command                                 Module                       Method URI                                                                             OutputType
-------                                 ------                       ------ ---                                                                             ----------
Get-MgChatMember                        Teams                        GET    /chats/{chat-id}/members                                                        IMicrosoftGr…
Get-MgDirectoryAdministrativeUnitMember Identity.DirectoryManagement GET    /directory/administrativeUnits/{administrativeUnit-id}/members                  IMicrosoftGr…
Get-MgDirectoryRoleMember               Identity.DirectoryManagement GET    /directoryRoles/{directoryRole-id}/members                                      IMicrosoftGr…
Get-MgEducationClassMember              Education                    GET    /education/classes/{educationClass-id}/members                                  IMicrosoftGr…
Get-MgExternalConnectionGroupMember     Search                       GET    /external/connections/{externalConnection-id}/groups/{externalGroup-id}/members IMicrosoftGr…
Get-MgGroupMember                       Groups                       GET    /groups/{group-id}/members                                                      IMicrosoftGr…
Get-MgGroupTeamMember                   Teams                        GET    /groups/{group-id}/team/members                                                 IMicrosoftGr…
Get-MgGroupTeamTagMember                Teams                        GET    /groups/{group-id}/team/tags/{teamworkTag-id}/members                           IMicrosoftGr…
Get-MgTeamMember                        Teams                        GET    /teams/{team-id}/members                                                        IMicrosoftGr…
Get-MgTeamTagMember                     Teams                        GET    /teams/{team-id}/tags/{teamworkTag-id}/members                                  IMicrosoftGr…
Get-MgUserChatMember                    Teams                        GET    /users/{user-id}/chats/{chat-id}/members                                        IMicrosoftGr…
```

**Comment by gavinbarron** [comment]
It appears that the underlying service issue is resolved based on my testing the requests succeeds for v2.27.0 and v2.32.0 on both v1 and beta, admittedly I was using delegated auth but the request succeeded. 

```powershell
 gavinbarron  import-module Microsoft.Graph.Teams -RequiredVersion 2.27.0
 gavinbarron  Get-MgTeamChannelMember -TeamId "d04b0b1c-1c19-43d5-92a3-1737a18f516b" -ChannelId "19:745a49ba9b1742b3825a7d1c138e2a04@thread.tacv2" -Debug
DEBUG: [CmdletBeginProcessing]: - Get-MgTeamChannelMember begin processing with parameterSet 'List'.
DEBUG: [Authentication]: - AuthType: 'Delegated', TokenCredentialType: 'InteractiveBrowser', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph Command Line Tools'.
DEBUG: [Authentication]: - Scopes: [Application.Read.All, Application.ReadWrite.All, AppRoleAssignment.ReadWrite.All, AuditLog.Read.All, BackupRestore-Configuration.Read.All, Calendars.Read, Calendars.ReadWrite, Chat.ReadBasic, ConsentRequest.Read.All, Device.ReadWrite.All, DeviceManagementManagedDevices.ReadWrite.All, DeviceManagementServiceConfig.ReadWrite.All, Directory.Read.All, Files.Read.All, Group.Read.All, Group.ReadWrite.All, GroupMember.ReadWrite.All, Mail.Read, openid, Policy.Read.All, Policy.ReadWrite.ApplicationConfiguration, Presence.Read, profile, RecordsManagement.Read.All, RoleManagement.Read.All, Sites.Read.All, Sites.ReadWrite.All, Team.ReadBasic.All, User.Read, User.Read.All, User.ReadWrite, User.ReadWrite.All, email, ChannelMember.Read.All].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/teams/d04b0b1c-1c19-43d5-92a3-1737a18f516b/channels/19%3A745a49ba9b1742b3825a7d1c138e2a04%40thread.tacv2/allMembers

Headers:
FeatureFlag                   : 00000003
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.26200; en-US),PowerShell/7.5.4
SdkVersion                    : graph-powershell/2.27.0
client-request-id             : 651263af-4778-4a26-8b21-ce27089c2a54
Accept-Encoding               : gzip,deflate,br

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 9df4c395-d2ff-4148-919b-edbcc4bd440d
client-request-id             : 651263af-4778-4a26-8b21-ce27089c2a54
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"West US 2","Slice":"E","Ring":"4","ScaleUnit":"000","RoleInstance":"CO1PEPF00011BA9"}}
odata-version                 : 4.0
Date                          : Mon, 10 Nov 2025 18:02:29 GMT

Body:
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#teams('d04b0b1c-1c19-43d5-92a3-1737a18f516b')/channels('19%3A745a49ba9b1742b3825a7d1c138e2a04%40thread.tacv2')/allMembers",
  "@odata.count": 16,
  "value": [
```

**Comment by jolscr** [comment]
The issue is still present, but the permission used is in application mode.

**Comment by Sekers** [comment]
I can also confirm that this issue still exists in version 2.32.0 using Application permissions.

**Comment by jolscr** [comment]
issue still exists in version 2.36.0 using Application permissions.

**Comment by jolscr** [comment]
Hello, any news about this ? want this to be fixed.

**Comment by jolscr** [comment]
The error disappeared regardless of the Microsoft Graph SDK version. Microsoft must have fixed it at their endpoint level.
