### ISSUE TITLE
Connect-MgGraph fails after Connect-ExchangeOnline

### ISSUE THREAD

**Issue by OtterKring** [microsoftgraph/msgraph-sdk-powershell#3394]
### Describe the bug

I don't know, if this is related to the ExchangeOnlineManagement module (my suspicison) or to Microsoft.Graph, but you should know; too, I guess:

I updated Microsoft.Graph from 2.29.1. to 2.30.0 yesterday and ExchangeOnlineManagement from 3.8.0 to 3.9.0. After the update I found that when I run Connect-ExchangeOnline before Connect-MgGraph, the latter fails with the following error:
```
Connect-MgGraph: ClientCertificateCredential authentication failed: Method not found: '!0 Microsoft.Identity.Client.BaseAbstractApplicationBuilder`1.WithLogging(Microsoft.IdentityModel.Abstractions.IIdentityLogger, Boolean)'.
```

When I run Connect-MgGraph first and then Connect-ExchangeOnline, it works.

### Expected behavior

IMO it should not matter, which command is run first.

### How to reproduce

- On Powershell 7.5.2 ... 
- Install Microsoft.Graph 2.30.0
- Install ExchangeOnlineManagement 3.9.0
- First run Connect-ExchangeOnline. ( I used certificate authentication )
- Second run Connect-MgGraph. It does not matter if user or certificate authentication. I tried both
- You should get the error described above

### SDK Version

2.30.0

### Latest version known to work for scenario above?

2.29.1 together with ExchangeOnlineManagement 3.8.0

### Known Workarounds

1) First run Connect-MgGraph
2) Then run Connect-ExchangeOnline

### Debug output

<details><summary>Click to expand log</summary>
```

DEBUG: ClientCertificateCredential.GetToken invoked. Scopes: [ https://graph.microsoft.com/.default ] ParentRequestId:
DEBUG: ClientCertificateCredential.GetToken was unable to retrieve an access token. Scopes: [ https://graph.microsoft.com/.default ] ParentRequestId:  Exception: Azure.Identity.AuthenticationFailedException (0x80131500): ClientCertificateCredential authentication failed: Method not found: '!0 Microsoft.Identity.Client.BaseAbstractApplicationBuilder`1.WithLogging(Microsoft.IdentityModel.Abstractions.IIdentityLogger, Boolean)'.
 ---> System.MissingMethodException (0x80131513): Method not found: '!0 Microsoft.Identity.Client.BaseAbstractApplicationBuilder`1.WithLogging(Microsoft.IdentityModel.Abstractions.IIdentityLogger, Boolean)'.
Connect-MgGraph: ClientCertificateCredential authentication failed: Method not found: '!0 Microsoft.Identity.Client.BaseAbstractApplicationBuilder`1.WithLogging(Microsoft.IdentityModel.Abstractions.IIdentityLogger, Boolean)'.

```
</details>

### Configuration

```
Name                           Value
----                           -----
PSVersion                      7.5.2
PSEdition                      Core
GitCommitId                    7.5.2
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Architecture: x64

**Comment by FabienTschanz** [comment]
The issue is with the assembly context of the module. Microsoft does not implement the assembly loading context properly, leading to those assemblies being loaded globally instead of only in the application context it belongs to. This is something that occurs again and again and they don't fix it... Guess we have to wait until the next release fixes it (for another couple of months until the next one)...

**Comment by robinmalik** [comment]
This has been an issue for years now as I remember having to inform colleagues to avoid doing this. Given that the Exchange team released a PowerShell **snap-in** just a few years ago despite modules being favoured since 2010, I'm not convinced they will be working collaboratively with more modern teams within Microsoft to help resolve this. I hope I'm wrong though.

**Comment by KevinPinel** [comment]
This does work in PS5. It doesn't help when scripts also rely on PS7 only modules

**Comment by gavinbarron** [comment]
We are working with the EXO team to resolve this issue and ensure it should not happen again.

In the meantime if you reverse the order in which the `Connect-*` cmdlets are called the cmdlets work as expected based on out testing

**Comment by Skaldhor** [comment]
@gavinbarron Is there any update regarding this issue?
It took more than a month to acknowledge the bug and now another month passed without a fix.
Since these are enterprise tools we need to manage our M365 services, I think there should be some kind of higher priority, rollback to working versions or some kind of communication at least.
I think there's no M365 admin center service incident, no message on the Exchange techcommunity Blog etc.

**Comment by mognify** [comment]
lol, pretty insane that it's fixed by importing ExchangeOnlineManagement **before** importing any Microsoft.Graph.* modules
but it works... very satisfying fix tbh... simple, straight-forward, reproducible with minimal effort...

I wonder what goes on that causes it to have issues if the Graph modules are imported first

**Comment by gavinbarron** [comment]
@Skaldhor we're trying to work with the EXO team on a comprehensive fix. 

I apologize that this is taking too long, but the reality here is that we have limited resources and the EXO team hasn't been willing to collaborate on a proper fix. So, while we could ship a fix that addresses this for the current versions without their collaboration, we'll wind up in the same broken state again when they ship again.

**Comment by Skaldhor** [comment]
@gavinbarron 
I understand there are internal collaboration issues at Microsoft and appreciate you being open about it and trying to achieve a future proof solution.

However, from a customer/consumer point of view: This is a bug/issue in enterprise management tools we need and pay for (indirectly). I would expect this to be fixed "relatively" timely, especially since you already seem to know the issue, cause and (potential) fix.
Even without the EXO team you could publish a working version for now and work on a future proof solution with them in the background.

**Comment by Steltek** [comment]
I now have the reverse issue:

```
PS C:\> Connect-MgGraph
Welcome to Microsoft Graph!

Connected via delegated access using 14d82eec-204b-4c2f-b7e8-296a70dab67e
Readme: https://aka.ms/graph/sdk/powershell
SDK Docs: https://aka.ms/graph/sdk/powershell/docs
API Docs: https://aka.ms/graph/docs

NOTE: You can use the -NoWelcome parameter to suppress this message.
NOTE: Sign in by Web Account Manager (WAM) is enabled by default on Windows systems and cannot be disabled when using the default ClientId.
To disable WAM run Set-MgGraphOption -DisableLoginByWAM $true and then use a custom ClientId.

PS C:\> Connect-ExchangeOnline
Error Acquiring Token:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker..ctor(CoreUIParent uiParent, ApplicationConfiguration appConfig, ILoggerAdapter logger)
   at Microsoft.Identity.Client.Broker.BrokerExtension.<>c.<AddRuntimeSupport>b__3_0(CoreUIParent uiParent, ApplicationConfiguration appConfig, ILoggerAdapter logger)
   at Microsoft.Identity.Client.PlatformsCommon.Shared.AbstractPlatformProxy.CreateBroker(ApplicationConfiguration appConfig, CoreUIParent uiParent)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.FetchTokensFromBrokerAsync(String brokerInstallUrl, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)
   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.MSALTokenProvider.GetAccessTokenAsync(String claims, String cmdletId)
OperationStopped: Object reference not set to an instance of an object.
PS C:\>
```

Inverting the commands and connecting to ExchangeOnline before Graph works. (If I want to add MicrosoftTeams to the same session, I have to connect to it before ExchangeOnline because those two modules also constantly conflict with one another.)

PowerShell: 7.5.4
Microsoft.Graph: 2.35.1
ExchangeOnlineManagement: 3.9.2
MicrosoftTeams: 7.6.0

This is really painful! Please write your PowerShell modules such that they will function regardless of what order they are loaded/started in.

**Comment by PimpJuiceIT** [comment]
Ridiculous, upon testing deprovisioning scripts post account termination, things not working even loading Exchange Online first. Now I have to spend time rewriting the logic in a way that works with the most up-to-date methods that work today to workaround the bugs (in all sections), and hope that it stays working or else redo it again on the next update for the next bug—I will remain hopeful it is not a continual issue that is reintroduced on the next release.

At least I run the module updates on a different VM machine for initial testing but would be nice for some consistency with updated modules. The order does seem to load to get a little further but run into other errors after that part of the logic is adjusted now. I modernized these scripts last round using a mix of Graph and Exchange Online commands. Now I need to figure out the order of logic for loading modules. 

For now, I'll hold off on updating my main machine until something is released fixing the bugs that were introduced which I can validate work without slews of time needed rewriting scripts and testing logic. In my case, on-prem is the source of authority and syncs over to M365 Entra Connect but before terminating accounts, all on-prem and Azure/Entra/Exchange Online details need documented in a pre-term text file.

**Comment by gaelcolas** [comment]
Working around this issue is a pain.

@gavinbarron Let me add that not implementing ALC will never properly fix the issue: https://github.com/jborean93/PowerShell-ALC
Without that, it will always depend on the MSAL signatures and backward compatibility, and which one is loaded first...
I'm sure if you reach out to the PS team internally (i.e. Steve L), he'll happily point you in the right direction.

For those looking for a temporary workaround to make your life slightly less miserable, @SamErde has build this workaround here: https://github.com/maester365/maester/blob/main/powershell/internal/Get-ModuleImportOrder.ps1#L1

**Comment by SteveL-MSFT** [comment]
See https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.5

**Comment by SteviebabesUK** [comment]
@SteveL-MSFT Fascinating read!
What I think those of us out in the field doing basic O365 user management on a day to day basis is for you guys to bang your heads together and stop this happening on an alarmingly regular basis for all of the key modules i.e. MGGraph, ExchangeOnline, PnP & Sharepoint.

**Comment by FabienTschanz** [comment]
And just found that there is another incompatibility with Microsoft Graph 2.35.1 and MicrosoftTeams 7.6.0. Doesn't matter which module is loaded first, if MicrosoftTeams is loaded, then `Connect-MgGraph` will fail:

```powershell
❯ Import-Module Microsoft.Graph.Authentication
❯ Import-Module MicrosoftTeams
❯ init # My wrapper function around Connect-MgGraph for easy initialization
Connect-MgGraph: C:\Users\...\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:64
Line |
  64 |      Connect-MgGraph -ApplicationId $clientId -TenantId $tenantIdName  …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | ClientCertificateCredential authentication failed: Method not found: '!0
     | Microsoft.Identity.Client.BaseAbstractApplicationBuilder`1.WithLogging(Microsoft.IdentityModel.Abstractions.IIdentityLogger, Boolean)'.
```

The issue is with the `Microsoft.IdentityModel.Abstractions.dll`, where Microsoft.Graph.Authentication uses `8.15.0.61118` and MicrosoftTeams uses `8.14.0.60815`.

```powershell
[appdomain]::currentdomain.GetAssemblies() | Where-Object Location -Like *identitymodel.abstractions*                                                                                                                                                                                                                                                                                            

GAC    Version        Location
---    -------        --------
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\2.35.1\Dependencies\Microsoft.IdentityModel.Abstractions.dll
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\7.6.0\netcoreapp3.1\Microsoft.IdentityModel.Abstractions.dll
```

How are we supposed to have a functioning environment if it only takes one single module to be update for nothing to work at the end? It's so frustrating, especially when we PowerShell module authors require several of those Graph, Exchange or Teams modules to be present for our work (looking at you M365DSC). I guess the only way for us to keep working is to spawn a new PowerShell job each time a new module is going to be loaded... Please do something about that.

**Comment by SamErde** [comment]
I just released v1.0 of my [**DLL Pickle**](https://github.com/SamErde/DLLPickle) module that prevents most cases of these DLL version conflicts. Please try it out and let me know your results!

```powershell
Install-Module -Name 'DLLPickle' -Scope CurrentUser
Import-Module -Name 'DLLPickle'
Import-DPLibrary
```

**Comment by marleyhehe** [comment]
Still a issue. :@

**Comment by PimpJuiceIT** [comment]
> Still a issue. :@

I’m encountering the issue still, even after installing and loading the DLLPickle module. 

Here's the detail list of the environment I'm working with:
- PowerShell Version: 7.6.0
- Microsoft.Graph Module: 2.36.1
- ExchangeOnlineManagement Module: 3.9.2
- Windows 11 Enterprise 25H2 (26200.7462)

Priming and connecting to **Exchange Online before connecting to Microsoft Graph helps resolve the issue**. Currently, I'm testing a V2 script with that as a workaround to get in some of the repetitions on account provisioning operations before updating my main system.

**Comment by Borgquite** [comment]
@FabienTschanz I found that when using Windows PowerShell 5.1, ExchangeOnlineManagement plays marginally better with Microsoft.Graph.* 2.36.1 if you downgrade to 3.9.0 instead of 3.9.2, at least in Azure Automation.

Also connect to Exchange Online before Microsoft Graph.

As far as I can see ExchangeOnlineManagement 3.9.2 doesn't appear to include any critical used by Microsoft365DSC so it could be worth downgrading. I wouldn't upgrade the modules until something critical is needed, or Microsoft actually finally resolve this.

**Comment by PrzemyslawKlys** [comment]
While we wait for MS to fix it I've added ALC automated handling to my PowerShell builder `Install-Module PSPublishModule`

```powershell
Import-Module PSPublishModule -Force

$exo = Import-IsolatedModule -Profile ExchangeOnlineManagement -PassThru
$teams = Import-IsolatedModule -Profile MicrosoftTeams -PassThru
$graph = Import-IsolatedModule -Profile MicrosoftGraphAuthentication -PassThru

Connect-ExchangeOnline -ShowBanner:$false
Connect-MicrosoftTeams
Connect-MgGraph -NoWelcome

Get-ConnectionInformation
Get-Team -NumberOfThreads 1
Get-MgContext

$exo, $teams, $graph | Format-Table ProfileName, ModuleName, ContextName
```

```powershell
Import-Module Microsoft.Graph.Authentication -Force
Import-Module PSPublishModule -Force

$exo = Import-IsolatedModule -Profile ExchangeOnlineManagement -PassThru
$exo | Format-List ProfileName, ModuleName, ContextName, IsolatedImportPath, WorkPath

Connect-ExchangeOnline -ShowBanner:$false
Get-EXOMailbox -ResultSize 1 | Select-Object DisplayName, PrimarySmtpAddress
Disconnect-ExchangeOnline -Confirm:$false
```


What it does:
- Finds the real installed module, for example ExchangeOnlineManagement or MicrosoftTeams.
- Copies it to a temporary work folder.
- Generates a patched wrapper .psm1.
- Loads the module’s selected DLLs through a named .NET AssemblyLoadContext, for example:
   - ExchangeOnlineManagement.ALC
   - MicrosoftTeams.ALC

Imports the PowerShell commands from those isolated assemblies.

Preserves the module manifest/export surface so users still run normal commands:

- Connect-ExchangeOnline
- Get-EXOMailbox
- Connect-MicrosoftTeams
- Get-Team

<img width="1820" height="678" alt="Image" src="https://github.com/user-attachments/assets/927de9e9-dd21-478f-900b-c636a426444b" />

This one proves it works also with DllPickle if that's your choice, but it shouldn't be nessecary

<img width="1730" height="1400" alt="Image" src="https://github.com/user-attachments/assets/386179a9-70cd-4750-ac2b-75be219c3679" />

```powershell
Import-Module Az.Storage -Force
Import-Module PSPublishModule -Force

$exo = Import-IsolatedModule -Profile ExchangeOnlineManagement -PassThru
$exo | Format-List ProfileName, ModuleName, ContextName, IsolatedImportPath, WorkPath

Connect-ExchangeOnline -ShowBanner:$false
Get-ConnectionInformation
Get-EXOMailbox -ResultSize 1 | Select-Object DisplayName, PrimarySmtpAddress
Disconnect-ExchangeOnline -Confirm:$false
```

```powershell
Import-Module Microsoft.Graph.Authentication -Force
Import-Module PSPublishModule -Force

$exo = Import-IsolatedModule -Profile ExchangeOnlineManagement -PassThru
$exo | Format-List ProfileName, ModuleName, ContextName, IsolatedImportPath, WorkPath

Connect-ExchangeOnline -ShowBanner:$false
Get-EXOMailbox -ResultSize 1 | Select-Object DisplayName, PrimarySmtpAddress
Disconnect-ExchangeOnline -Confirm:$false
```

```powershell
Import-Module Microsoft.Graph.Authentication -Force
Import-Module PSPublishModule -Force

$teams = Import-IsolatedModule -Profile MicrosoftTeams -PassThru
$teams | Format-List ProfileName, ModuleName, ContextName, IsolatedImportPath, WorkPath

Connect-MicrosoftTeams
Get-Team | Select-Object -First 5 DisplayName, GroupId, Visibility
Disconnect-MicrosoftTeams
```

```powershell
Import-Module Az.Accounts -Force
Import-Module PSPublishModule -Force

$teams = Import-IsolatedModule -Profile MicrosoftTeams -PassThru
$teams | Format-List ProfileName, ModuleName, ContextName, IsolatedImportPath, WorkPath

Connect-MicrosoftTeams
Get-CsTenant | Select-Object DisplayName, TenantId
Disconnect-MicrosoftTeams
```

```powershell
Import-Module Az.Accounts -Force
Import-Module Az.Storage -Force
Import-Module Microsoft.Graph.Authentication -Force
Import-Module PSPublishModule -Force

$exo = Import-IsolatedModule -Profile ExchangeOnlineManagement -PassThru
$teams = Import-IsolatedModule -Profile MicrosoftTeams -PassThru

Connect-ExchangeOnline -ShowBanner:$false
Get-EXOMailbox -ResultSize 1 | Select-Object DisplayName, PrimarySmtpAddress

Connect-MicrosoftTeams
Get-Team | Select-Object -First 5 DisplayName, GroupId, Visibility

Disconnect-MicrosoftTeams
Disconnect-ExchangeOnline -Confirm:$false
```

**Comment by 12Knocksinna** [comment]
Still problems with Graph SDK V2.38 and Exchange Online Management 3.10. Have protested to the Exchange Online PowerShell team and whined at @gavinbarron.

https://office365itpros.com/2026/06/22/powershell-woes-and-cmdlets/

**Comment by 12Knocksinna** [comment]
Running Connect-ExchangeOnline -DisableWAM allows Exchange to connect after a Graph connection is established. While you could argue that this fixes the problem, there are tons of customer production scripts in active use today that don't specify DisableWAM and that's the reason why the problem needs to be fixed.

**Comment by 12Knocksinna** [comment]
This works with PowerShell 5.1:

Import-Module Microsoft.Graph.Authentication -RequiredVersion 2.38.0
Import-Module ExchangeOnlineManagement -RequiredVersion 3.10.0
Connect-MgGraph
Connect-ExchangeOnline

Again, it's just a workaround that might be acceptable for some but not for organizations that have to update production scripts or who have standardized on PowerShell Core.

**Comment by tymondouglas** [comment]
Will this ever get fixed?
I had to fall back to ExchangeOnlineManagement 3.6.0 for now.

**Comment by imbaru-design** [comment]
> I just released v1.0 of my [**DLL Pickle**](https://github.com/SamErde/DLLPickle) module that prevents most cases of these DLL version conflicts. Please try it out and let me know your results!
> 
> Install-Module -Name 'DLLPickle' -Scope CurrentUser
> Import-Module -Name 'DLLPickle'
> Import-DPLibrary

this works with zero drama. cheers 🍺

**Comment by Mike-Crowley** [comment]
Confirming this is still present on the current latest: PowerShell 7.6.6, Microsoft.Graph.Authentication 2.40.0, ExchangeOnlineManagement 3.10.1. EXO-then-Graph gives the WithLogging method-not-found; Graph-then-EXO gives the RuntimeBroker NullReferenceException.

One refinement to the version-conflict framing above (e.g. @FabienTschanz's 8.15-vs-8.14 note): I traced the assembly binding, and matching the MSAL versions does not help. Both modules now ship the same Microsoft.Identity.Client (4.83.1) and the same native msalruntime, and it still fails. The break is cross-context type identity, not a version delta:

- EXO loads its MSAL and Microsoft.IdentityModel.Abstractions into the Default AssemblyLoadContext.
- msgraph-load-context has no Load override, so anything Graph does not load itself falls back to Default.
- Loading second, Graph's Azure.Identity binds to EXO's MSAL already resident in Default. That MSAL's WithLogging is typed to the IIdentityLogger from Default's Abstractions, while Azure.Identity passes the IIdentityLogger from its own context. Same type name, two ALCs, two identities, so the method will not bind.

The practical implication: even a release that perfectly aligned every MSAL version would still break as long as EXO populates Default and Graph falls back into it. More evidence for what @gaelcolas and @PrzemyslawKlys already said, that EXO needs to load into its own ALC. Until then the isolation wrappers in this thread (DLLPickle, PSPublishModule's Import-IsolatedModule) are the only clean fixes; -DisableWAM sidesteps the Graph-first NullReferenceException but not the WithLogging clash.

**Comment by SamErde** [comment]
> Confirming this is still present on the current latest: PowerShell 7.6.6, Microsoft.Graph.Authentication 2.40.0, ExchangeOnlineManagement 3.10.1. EXO-then-Graph gives the WithLogging method-not-found; Graph-then-EXO gives the RuntimeBroker NullReferenceException.
> 
> One refinement to the version-conflict framing above (e.g. [Fabien Tschanz (@FabienTschanz)](https://github.com/FabienTschanz)'s 8.15-vs-8.14 note): I traced the assembly binding, and matching the MSAL versions does not help. Both modules now ship the same Microsoft.Identity.Client (4.83.1) and the same native msalruntime, and it still fails. The break is cross-context type identity, not a version delta:
> 
> * EXO loads its MSAL and Microsoft.IdentityModel.Abstractions into the Default AssemblyLoadContext.
> * msgraph-load-context has no Load override, so anything Graph does not load itself falls back to Default.
> * Loading second, Graph's Azure.Identity binds to EXO's MSAL already resident in Default. That MSAL's WithLogging is typed to the IIdentityLogger from Default's Abstractions, while Azure.Identity passes the IIdentityLogger from its own context. Same type name, two ALCs, two identities, so the method will not bind.
> 
> The practical implication: even a release that perfectly aligned every MSAL version would still break as long as EXO populates Default and Graph falls back into it. More evidence for what [gaelcolas (@gaelcolas)](https://github.com/gaelcolas) and [Przemysław Kłys (@PrzemyslawKlys)](https://github.com/PrzemyslawKlys) already said, that EXO needs to load into its own ALC. Until then the isolation wrappers in this thread (DLLPickle, PSPublishModule's Import-IsolatedModule) are the only clean fixes; -DisableWAM sidesteps the Graph-first NullReferenceException but not the WithLogging clash.

Nice summary. Do you have an agent skill that checks to see if open issues are still relevant or have any potential new resolutions?

**Comment by Mike-Crowley** [comment]
No, that was a one-off as a result of trying to work through the mechanics
