### ISSUE TITLE
Body of request is not shown in debug 

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#980]
Expected: Body would show the JSONified request for the new group.
Actual: Nothing is shown. I have to go to fiddler or similar capture mechanism to see it.

```
❯ $x | new-mggroup -verbose -debug
DEBUG: [CmdletBeginProcessing]: - New-MgGroup begin processing with parameterSet 'Create'.
DEBUG: [Authentication]: - AuthType: 'Delegated', AuthProviderType: 'InteractiveAuthenticationProvider', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph PowerShell'.
DEBUG: [Authentication]: - Scopes: [Directory.AccessAsUser.All, EntitlementManagement.Read.All, EntitlementManagement.ReadWrite.All, openid, PrivilegedAccess.ReadWrite.AzureAD, PrivilegedAccess.ReadWrite.AzureADGroup, PrivilegedAccess.ReadWrite.AzureResources, profile, User.Read, email].

Confirm
Are you sure you want to perform this action?
Performing the operation "New-MgGroup_Create" on target "Call remote 'GroupsGroupCreateGroup' operation".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://graph.microsoft.com/v1.0/groups

Headers:
SdkVersion                    : Graph-powershell-1.9.0,Graph-dotnet-1.25.1
FeatureFlag                   : 00000047
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.22000; en-US),PowerShell/7.2.0,New-MgGroup_Create
Accept-Encoding               : gzip

Body:


```

**Comment by peombwa** [comment]
Thanks for surfacing this. We've already fixed the issue, and a fix will be released as part of our 1.9.1 release: https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/982.

**Comment by JustinGrote** [comment]
@peombwa thank you!

**Comment by jasonjoh** [comment]
@peombwa I'm still seeing no body in `-Debug` output for New-MgApplication.

```powershell
New-MgApplication -DisplayName "PS Test" -SignInAudience "AzureADMyOrg" -Verbose -Debug
```

**Comment by maisarissi** [comment]
Yes. Same here:
![image](https://user-images.githubusercontent.com/22648831/152243055-d1e762ed-b416-40f4-80a2-2eb20c07863e.png)

**Comment by elygre** [comment]
I'm experiencing the same problem, using version 1.9.2:

```
PS C:\> Get-Command Get-MgOrganization

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-MgOrganization                                 1.9.2      Microsoft.Graph.Identity.DirectoryManagement

PS C:\> Get-MgOrganization -verbose -debug
DEBUG: [CmdletBeginProcessing]: - Get-MgOrganization begin processing with parameterSet 'List'.
DEBUG: [Authentication]: - AuthType: 'Delegated', AuthProviderType: 'InteractiveAuthenticationProvider', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph PowerShell'.
DEBUG: [Authentication]: - Scopes: [Group.ReadWrite.All, openid, profile, RoleManagement.Read.Directory, User.Read, User.Read.All, email, RoleManagement.ReadWrite.Directory].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/beta/organization

Headers:
SdkVersion                    : graph-powershell/1.9.2,Graph-dotnet-1.25.1
FeatureFlag                   : 00000047
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.19042; nb-NO),PowerShell/7.2.1,Get-MgOrganization_List
Accept-Encoding               : gzip

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 2df71466-238c-48e9-ad55-60c908f2f303
client-request-id             : 2df71466-238c-48e9-ad55-60c908f2f303
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"West Europe","Slice":"E","Ring":"5","ScaleUnit":"004","RoleInstance":"AM2PEPF00005518"}}
x-ms-resource-unit            : 1
OData-Version                 : 4.0
Date                          : Sat, 05 Feb 2022 14:22:45 GMT

Body:




DEBUG: [CmdletEndProcessing]: - Get-MgOrganization end processing.

```

**Comment by pri-kise** [comment]
> @peombwa I'm still seeing no body in `-Debug` output for New-MgApplication.
> 
> ```powershell
> New-MgApplication -DisplayName "PS Test" -SignInAudience "AzureADMyOrg" -Verbose -Debug
> ```

I'm having the same problem that my request body is still empty with version 1.9.3.

**Comment by JustinGrote** [comment]
While this does need to be fixed, as a workaround you can use Fiddler Classic on windows and intercept the traffic to see it.

**Comment by maisarissi** [comment]
@peombwa Can you validate this? It seems like the issue hasn't been fixed yet.

**Comment by peombwa** [comment]
The issue with the request body missing seems to be isolated to PowerShell 5.1. @pri-kise, as a workaround, can you [upgrade your PowerShell version to 7+](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2), which does not have this issue.
